### ISSUE TITLE
Difference between tests.json vs spec_tests.json?

### ISSUE THREAD

**Issue by sergkr** [json-patch/json-patch-tests#16]
I'm currently working on contributing to one of the implementations for JSON Patch ([myquay/JsonPatch](https://github.com/myquay/JsonPatch)) and came across these tests.

I'm just wondering... Is there a reason why the tests are split across two different files?  Are conforming implementations supposed to pass all the tests in both files (minus the ones marked disabled)? If there's any significance to this split, could this be clarified in the README?

**Comment by mikemccabe** [comment]
Thanks for your interest!  The spec_tests.json file is a copy of the tests from the spec itself.  They're redundant against the main test file.  You would be OK with just tests.json.

I'll add this to the README.
