### ISSUE TITLE
Disable replace root document tests

### ISSUE THREAD

**Issue by sonnyp** [json-patch/json-patch-tests#18]
I'm wondering if the following tests

* [replacing the root of the document is possible with add](https://github.com/json-patch/json-patch-tests/blob/master/tests.json#L279)
* [replace whole document](https://github.com/json-patch/json-patch-tests/blob/master/tests.json#L174)

shouldn't be disabled by default.

It seems rather implementation specific and as far as I know the expected behavior isn't specified in the RFC.

On a similar subject, the test for testing the all document is disabled. [Whole document](https://github.com/json-patch/json-patch-tests/blob/master/tests.json#L229)
Not sure why though, contrary to the previous mentioned it looks rather straightforward.

**Comment by mikemccabe** [comment]
Thanks for the interest!  These are in the spec, so they should stay in the tests.

**Comment by mikemccabe** [comment]
Relevant bit:

For example:

   { "op": "add", "path": "/a/b/c", "value": [ "foo", "bar" ] }

   When the operation is applied, the target location MUST reference one
   of:

   o  The root of the target document - whereupon the specified value
      becomes the entire content of the target document.

...

**Comment by sonnyp** [comment]
my bad, missed it

thanks

What about https://github.com/json-patch/json-patch-tests/blob/master/tests.json#L229 should it be enabled?
