### ISSUE TITLE
A.14 example

### ISSUE THREAD

**Issue by mnot** [json-patch/json-patch-tests#22]
Putting this here because much of the community pays more attention here than to IETF lists - 

We received an errata report on JSON Patch that asks to change the A.14 example; see
  http://www.rfc-editor.org/errata_search.php?rfc=6902&eid=4419

At first glance, it seems reasonable to me (although really it's a text improvement, not an errata); any thoughts?

**Comment by brettz9** [comment]
FWIW, I see other people had trouble with this section's example too: http://stackoverflow.com/questions/24419391/how-is-the-tilde-escaping-in-the-json-patch-rfc-supposed-to-operate
