### ISSUE TITLE
Escape JSON Patch Path for Key with Backslash

### ISSUE THREAD

**Issue by austince** [json-patch/json-patch-tests#42]
How would one create the object { "valid/key": true } with JSON Patch? I can't find anything in the RFC.

**Comment by raymccrae** [comment]
JSON Patch uses JSON Pointers to specify the path to elements of the JSON document. The answer you're looking for is documented in [RFC6901, section 3](https://tools.ietf.org/html/rfc6901#section-3). "~"_(tilde)_ is encoded as "~0" and "/"_(forward slash)_ is encoded as "~1".

```
[{"op": "add",  "path": "valid~1key", "value": true}]
```

**Comment by austince** [comment]
Ah great, thank you for pointing me there!
